[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
selene = { source = "Kampfkarren/selene", version = "0.18.1" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.13.1" }
luau-analyze = { source = "JohnnyMorganz/luau-analyze-rojo", version = "0.527.0" }
wally = { source = "UpliftGames/wally", version = "0.3.1" }
